Nrfx none init new repo
NordicSemiconductor/npmx-zephyr pull request #1
Opened 2023-05-19 14:24 UTC by wilu-nordic

2023-05-23 10:17 UTC, masz-nordic commented on doc/index.rst
> +   sidewalk_known_issues.rst
```suggestion
```

2023-05-23 10:17 UTC, masz-nordic commented on drivers/npmx/Kconfig
> +	bool "Enabling npmx"
```suggestion
	bool "Enable npmx"
```

2023-05-23 12:40 UTC, masz-nordic commented on zephyr/module.yml
> +  kconfig: Kconfig.nrf
```suggestion
  kconfig: Kconfig
```

2023-05-24 14:10 UTC, masz-nordic commented on west.yml
> +      repo-path: zephyr
Can be skipped, it's taken from `name` by default.

2023-05-24 14:33 UTC, masz-nordic commented on drivers/CMakeLists.txt
> +# Copyright (c) 2018-2020 Nordic Semiconductor ASA
```suggestion
# Copyright (c) 2023 Nordic Semiconductor ASA
```

2023-05-24 14:42 UTC, masz-nordic commented on scripts/install_hooks.py
> +import os
Missing license

2023-05-24 14:43 UTC, masz-nordic commented on west.yml
> +    # nRF Connect SDK base URL.
```suggestion
```

2023-05-24 14:43 UTC, masz-nordic commented on west.yml
> +  projects:
```suggestion
      url-base: https://github.com/zephyrproject-rtos

  projects:
```

2023-05-24 14:44 UTC, masz-nordic commented on west.yml
> +      remote: NordicSemiconductor
```suggestion
```

2023-05-24 14:54 UTC, magp-nordic approved these changes

2023-05-24 15:03 UTC, masz-nordic submitted a review, later dismissed

2023-05-25 07:54 UTC, mkleszcz-no submitted a review, later dismissed

2023-05-25 10:18 UTC, annakielar requested changes

2023-05-25 10:18 UTC, annakielar commented on drivers/npmx/npmx_glue.c
> +	/* Send the address to write to. */
```suggestion
	/* Send the address to where data is to be written. */
```

2023-05-25 10:18 UTC, annakielar commented on drivers/npmx/npmx_glue.c
> +	/* Send the address to read from. */
```suggestion
	/* Send the address where data is to be read from. */
```

2023-05-25 10:18 UTC, annakielar commented on drivers/npmx/npmx_glue.h
> + * @brief Write I2C.
```suggestion
 * @brief Function for writing I2C.
```

2023-05-25 10:18 UTC, annakielar commented on drivers/npmx/npmx_glue.h
> + * @retval NPMX_SUCCESS  If successful.
```suggestion
 * @retval NPMX_SUCCESS  Writing I2C was successful.
```

2023-05-25 10:18 UTC, annakielar commented on drivers/npmx/npmx_glue.h
> + * @brief Read I2C.
```suggestion
 * @brief Function for reading I2C.
```

2023-05-25 10:18 UTC, annakielar commented on drivers/npmx/npmx_glue.h
> + * @retval NPMX_SUCCESS  If successful.
```suggestion
 * @retval NPMX_SUCCESS  Reading I2C was successful.
```

2023-05-25 10:18 UTC, annakielar commented on drivers/npmx/npmx_shell.c
> +/* creating subcommands (level 3 command) array for command "vbusin status". */
```suggestion
/* Creating subcommands (level 3 command) array for command "vbusin status". */
```

2023-05-25 10:18 UTC, annakielar commented on drivers/npmx/npmx_shell.c
> +/* Creating root (level 0) command "npmx" without a handler */
```suggestion
/* Creating root (level 0) command "npmx" without a handler. */
```

2023-05-25 10:50 UTC, wilu-nordic commented on drivers/npmx/npmx_glue.h
> + * @brief This file contains functions declarations and macros that should be implemented
Yes.

2023-05-25 11:31 UTC, annakielar requested changes

2023-05-25 11:31 UTC, annakielar commented on drivers/npmx/npmx_driver.c
> +	/* Disable both POF and interrupt pin in case of POF activation. */
```suggestion
	/* Disable both POF and interrupt pins in case of POF activation. */
```

2023-05-25 11:31 UTC, annakielar commented on drivers/npmx/npmx_driver.h
> + * @return Return POF pin index.
```suggestion
 * @return POF pin index.
```
Please remove all "Return" verbs from return messages.

2023-05-25 11:31 UTC, annakielar commented on drivers/npmx/npmx_driver.h
> + * @brief Get reset pin index from nPM Zephyr device.
```suggestion
 * @brief Function for getting reset pin index from nPM Zephyr device.
```

2023-05-25 11:31 UTC, annakielar commented on drivers/npmx/npmx_shell.c
> +		shell_error(shell, "Error: uanble to read charging current value.");
```suggestion
		shell_error(shell, "Error: unable to read charging current value.");
```

2023-05-25 11:40 UTC, annakielar approved these changes

2023-05-25 11:41 UTC, masz-nordic approved these changes

2023-05-25 11:51 UTC, mkleszcz-no approved these changes

2023-05-25 12:09 UTC, merged