samples: add shell
NordicSemiconductor/npmx-zephyr pull request #15
Opened 2023-05-31 14:38 UTC by wilu-nordic

2023-06-05 09:29 UTC, annakielar requested changes

2023-06-05 09:38 UTC, annakielar approved these changes

2023-06-05 09:47 UTC, mkleszcz-no approved these changes

2023-06-05 09:48 UTC, masz-nordic commented on samples/shell/sample.yaml
> +  sample.shell_example_eng_b:
```suggestion
  sample.shell.eng_b:
```

2023-06-05 09:48 UTC, masz-nordic commented on samples/shell/README.rst
> +* Initialize and register a POF callback.
```suggestion
This sample does the following:

* Configures the Zephyr shell driver.
* Initializes and registers a POF callback.
```
What do you think @annakielar ?

2023-06-05 09:50 UTC, annakielar commented on samples/shell/README.rst
> +* Initialize and register a POF callback.
Ohhh my bad. Definitely yes.

2023-06-05 09:52 UTC, wilu-nordic commented on samples/shell/README.rst
> +* Initialize and register a POF callback.
FIxed

2023-06-05 11:50 UTC, wilu-nordic commented on samples/shell/README.rst
> +The SHELL sample allows to use the Zephyr shell to control a PMIC device.
Zephyr Shell driver

2023-06-05 11:54 UTC, annakielar approved these changes

2023-06-05 13:11 UTC, wilu-nordic commented on samples/shell/README.rst
> +* Initialize and register a POF callback.
What about `The Shell sample allows to control a PMIC device with the Zephyr Shell driver.`?

2023-06-05 13:56 UTC, annakielar requested changes

2023-06-05 13:56 UTC, annakielar commented on samples/shell/README.rst
> +This sample does the following:
```suggestion
This sample allows to do the following:
```

2023-06-05 15:24 UTC, wilu-nordic commented on samples/shell/README.rst
> +The Shell sample allows to control a PMIC device with command set using the Zephyr shell module.
Yes

2023-06-06 05:47 UTC, annakielar commented on samples/shell/README.rst
> +The Shell sample allows to control a PMIC device with a command set and using the Zephyr shell module.
```suggestion
The Shell sample allows to control a PMIC device using a command set and the Zephyr shell module.
```

2023-06-06 06:54 UTC, annakielar approved these changes

2023-06-06 08:34 UTC, masz-nordic commented on samples/shell/README.rst
> +The Shell sample allows to control a PMIC device with command set using the Zephyr shell module.
No, the command set is built using the shell module.

2023-06-06 09:07 UTC, annakielar commented on samples/shell/README.rst
> +#. |connect_terminal|
Any sample-specific steps?

2023-06-06 10:14 UTC, annakielar commented on samples/shell/README.rst
> +#. Review and use npmx commands in the Shell.
```suggestion
#. Review available npmx commands, and use the relevant ones in the shell.
```

2023-06-06 11:21 UTC, masz-nordic approved these changes

2023-06-06 11:34 UTC, annakielar approved these changes

2023-06-06 11:57 UTC, merged