Pmic samples ldo
NordicSemiconductor/npmx-zephyr pull request #4
Opened 2023-05-23 07:26 UTC by wilu-nordic

Only the last commit should be checked.

2023-06-06 11:48 UTC, annakielar requested changes

2023-06-06 11:48 UTC, annakielar commented on samples/ldo/README.rst
> +The LDO sample demonstrates how to control LDOs using npmx drivers.
```suggestion
The LDO sample demonstrates how to control LDOs with the use of npmx drivers.
```

2023-06-06 11:48 UTC, annakielar commented on samples/ldo/src/main.c
> +		/* Wait some time to stabilize and measure the output voltage. */
```suggestion
		/* Wait some time for the output voltage to stabilize, and measure it. */
```

2023-06-06 11:48 UTC, annakielar commented on samples/ldo/src/main.c
> +	/* Have to be called each time to change output voltage. */
```suggestion
	/* Has to be called each time to change output voltage. */
```

2023-06-06 12:30 UTC, annakielar submitted a review, later dismissed

2023-06-13 09:25 UTC, annakielar approved these changes

2023-06-13 09:44 UTC, masz-nordic approved these changes

2023-06-13 09:45 UTC, merged