samples: timer wakeup
NordicSemiconductor/npmx-zephyr pull request #9
Opened 2023-05-23 07:37 UTC by wilu-nordic

2023-06-14 11:01 UTC, annakielar commented on samples/timer_wakeup/src/main.c
> +	/* Save compare value data to internal timer's registers. */
```suggestion
	/* Save the compare value data to internal timer's registers. */
```

2023-06-14 11:27 UTC, wilu-nordic commented on samples/timer_wakeup/README.rst
> +  * Configure TIMER in wake-up mode.
Periphery

2023-06-14 11:28 UTC, wilu-nordic commented on samples/timer_wakeup/README.rst
> +#. LEDs is used to indicate when the PMIC wakes up.
The LED is on when PMIC is up.

2023-06-14 12:58 UTC, annakielar requested changes

2023-06-14 12:58 UTC, annakielar commented on samples/timer_wakeup/README.rst
> +LEDs are used to indicate when the PMIC wakes up.
Here we should have a result of testing actions, so the sentence is in a correct place but we need to change its structure, for example:
```suggestion
LEDs will start blinking when the PMIC wakes up.
```

2023-06-14 12:58 UTC, annakielar commented on samples/timer_wakeup/src/main.c
> + * @brief Function for blinking LEDs.
```suggestion
 * @brief Function for enabling LEDs to blink.
```
Is it correct?

2023-06-15 06:38 UTC, annakielar requested changes

2023-06-15 06:38 UTC, annakielar commented on samples/timer_wakeup/README.rst
> +The Wake-up Timer sample demonstrates how to use the PMIC TIMER periphery and SHIPHLD button with npmx drivers.
```suggestion
The Wake-up Timer sample demonstrates how to use the PMIC TIMER periphery and the SHIPHLD button with npmx drivers.
```

2023-06-15 09:31 UTC, annakielar commented on samples/timer_wakeup/README.rst
> +#. Wait for ~8 seconds until device wakes up.
```suggestion
#. Wait for ~8 seconds until the device wakes up.
```

2023-06-15 09:37 UTC, annakielar commented on samples/timer_wakeup/README.rst
> +LED is on when the PMIC wakes up.
```suggestion
When the PMIC wakes up, the LED will turn on.
```

2023-06-15 10:02 UTC, annakielar approved these changes

2023-06-15 12:36 UTC, annakielar approved these changes

2023-06-16 10:55 UTC, masz-nordic commented on samples/timer_wakeup/README.rst
> +#. Press the SW1 (SHPHLD) button to enter the hibernate mode.
`hibernate mode` or `hibernation mode`?

2023-06-16 11:22 UTC, masz-nordic approved these changes

2023-06-16 11:22 UTC, merged